
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.0.11-alpine
    container_name: wechat_redis
    privileged: true
    volumes:
      - ./.redis/data:/data
      - ./.conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.redis/logs:/logs
    command: ["redis-server"]
    ports:
      - 6379:6379

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"     # AMQP 协议端口
      - "15672:15672"   # 管理界面端口
    volumes:
      - "./data:/var/lib/rabbitmq"  # 持久化RabbitMQ数据
    environment:
      RABBITMQ_DEFAULT_USER: "user"     # 设置默认用户名
      RABBITMQ_DEFAULT_PASS: "password" # 设置默认密码
    restart: always
