
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis:7.0.11-alpine
    container_name: wechat_redis
    privileged: true
    volumes:
      - ./.redis/data:/data
      - ./.conf/redis.conf:/usr/local/etc/redis/redis.conf
      - ./.redis/logs:/logs
    command: ["redis-server"]
    ports:
      - 6379:6379