// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type Apply struct {
	ID          int64  `json:"id"`
	ApplicateID string `json:"applicate_id"`
	TargetID    string `json:"target_id"`
	// 消息类型,0为群申请,1为私人申请
	AType int32 `json:"a_type"`
}

type Friend struct {
	ID        int64     `json:"id"`
	FUserID   string    `json:"f_user_id"`
	TUserID   string    `json:"t_user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Group struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Account   string    `json:"account"`
	Owner     string    `json:"owner"`
	CreatedAt time.Time `json:"created_at"`
}

type GroupMember struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	GroupID   string    `json:"group_id"`
	UserID    string    `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
}

type Message struct {
	ID         int64          `json:"id"`
	Content    sql.NullString `json:"content"`
	FromUserID string         `json:"from_user_id"`
	ToUserID   sql.NullString `json:"to_user_id"`
	GroupID    sql.NullString `json:"group_id"`
	// 消息类型,0为群消息,1为私人消息
	MType int32 `json:"m_type"`
	// 0为在线,1为离线
	Networktatus int32     `json:"networktatus"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID                int64     `json:"id"`
	Username          string    `json:"username"`
	HashedPassword    string    `json:"hashed_password"`
	Phone             string    `json:"phone"`
	Account           string    `json:"account"`
	Token             string    `json:"token"`
	AccountChangedAt  time.Time `json:"account_changed_at"`
	PhoneChangedAt    time.Time `json:"phone_changed_at"`
	UsernameChangedAt time.Time `json:"username_changed_at"`
	PasswordChangedAt time.Time `json:"password_changed_at"`
	CreatedAt         time.Time `json:"created_at"`
}
